seed: 42

wandb:
  project: "Pendulum-SystemID-Arena"
  run_name: "CNNLSTM-SL-Baseline"

model:
  chkpt_path: "./models/best_sysid_model_sl.pth"
  rl_chkpt_path: "./models/best_sysid_model_sl_with_rl.pth"

hyperparameters:
  state_dims: 5
  action_dims: 1
  learning_rate: 0.0001
  cnn1_dims: 128  # This means it is cnn1_dims * 4 parallel CNNS * 2 (state + action)
  cnn2_dims: 128  # This outputs cnn2_dims * 4 features to the lstm
  lstm_dims: 64
  weight_decay: 0.0
  clip_value: 5.0
  batch_size: 512
  epochs: 1000
  min_steps: 50

dataset:
  # For data collection
  # Formula for total timesteps is 2^m * number_of_signal_types * episode_length = total_timesteps
  # m = round(log2(desired_total_timesteps / (number_of_signal_types * episode_length)))
  collection_signal_types: ["noise", "prbs", "multisine", "impulse", "chirp_normal", "chirp_normal", "chirp_shifted", "chirp_shifted", "chirp_shifted", "chirp_shifted"]
  # collection_signal_types: ["impulse"]  # Only impulse

  # You must run collection twice one for training and one for OOD
  # --- For training ---
  # desired_total_timesteps: 5000000
  desired_total_timesteps: 20000000  # Can change when it doesn't follow power of 2
  chosen_bounds: "sysid_bounds" # options are "sysid_bounds" or "sysid_absolute_bounds"
  raw_path: "./dataset/raw_pendulum_sysid_dataset.npz"
  # --- For true OOD ---
  # desired_total_timesteps: 1000000  # Can change when it doesn't follow power of 2
  # chosen_bounds: "sysid_absolute_bounds" # options are "sysid_bounds" or "sysid_absolute_bounds"
  # raw_path: "./dataset/raw_ood_pendulum_sysid_dataset.npz"

  # For preprocessing with RL collected data
  # DEFAULT IS FALSE
  include_rl_dataset: True  # Overrides the scalers path above if True
  use_sl_with_rl_model: True  # If True, uses the SL model trained with RL data for the RL explorer
  rl_raw_processed_path: "./dataset/raw_processed_rl_pendulum_dataset.npz"
  rl_scalers_path: "./models/rl_scalers.pkl"
  rl_processed_path: "./dataset/processed_rl_pendulum_dataset.npz"

  # For preprocessing and viewing the dataset
  encoder_resolution: 4096.0 # 12-bit encoder
  figures_path: "./dataset/figures"
  scalers_path: "./models/scalers.pkl"
  processed_path: "./dataset/processed_pendulum_sysid_dataset.npz"
  # If you want to skip the noise/quantization step and just use the raw data with engineered features, use this path instead:
  # processed_path: "./dataset/processed_clean_pendulum_sysid_dataset.npz"

nominal_params:
  kp: 998.22
  kv: 2.731
  max_torque: 2.94
  frictionloss: 0.052
  damping: 0.6
  armature: 0.028
  backlash_max_deg: 0.87
  backlash_armature: 0.01
  backlash_damping: 0.01

# Pruned
# This includes OOD + ID for training
sysid_bounds:
  frictionloss: [0.02, 0.8]
  damping: [0.2, 2.0]
  armature: [0.01, 0.16]
  backlash_armature: [0.001, 0.1]
  backlash_damping: [0.001, 1.0]

# This is the absolute bounds and only used after training for evaluation
sysid_absolute_bounds:
  frictionloss: [0.001, 1.0]
  damping: [0.001, 3.0]
  armature: [0.001, 0.2]
  backlash_armature: [0.0001, 0.2]
  backlash_damping: [0.0, 2.0]
