seed: 42

dataset:
  # Formula here is 2^m * number_of_signal_types * episode_length = total_timesteps
  # m = round(log2(desired_total_timesteps / (number_of_signal_types * episode_length)))
  desired_total_timesteps: 20000000  # Can change when it doesn't follow power of 2
  raw_path: "./dataset/raw_pendulum_sysid_dataset.npz"

# Pruned 
dr_absolute_bounds:
  kp: [10.0, 2000.0]
  kv: [0.2, 20.0]
  max_torque: [2.0, 5.0]
  frictionloss: [0.001, 1.0]
  armature: [0.001, 0.2]
  backlash_max_deg: [0.5, 1.3]
